"""Every password already in the database must still verify.

`app/utils/passwords.py` used to delegate to passlib; it now implements the
`bcrypt_sha256` scheme itself, against the `bcrypt` package directly, because
passlib 1.7.4 (unchanged since 2020) reads `bcrypt.__about__.__version__` and
probes the backend by hashing a >72-byte secret — so it cannot import at all
against bcrypt 4.1+, which froze us on bcrypt 4.0.1 (`docs/decisions.md` §151).

The one thing that could go wrong is the digest: `bcrypt_sha256` is NOT
`bcrypt(sha256(password))`. It is an HMAC-SHA256 keyed off the *encoded* salt
text, base64-encoded (not hex) before bcrypt sees it, in a specific string
format that differs between the scheme's v1 and v2. Get any of that wrong and
every stored credential stops verifying — a silent, total lockout that no unit
test of our own round trip would catch, because our own hash and our own verify
would agree with each other perfectly while disagreeing with the column.

So the hashes below are **fixtures passlib itself produced**, pasted in as
literals. The test never imports passlib (it is no longer a dependency); the
literals are the only remaining record of what it emitted, which is exactly why
they are hard-coded rather than generated. Regenerating them requires a passlib
install and is not something a change to our code should ever need.

Covered: v2 (the current format), v1 (pre-passlib-1.7.3, still read), both the
`2b` and the legacy `2a` bcrypt variants, and the plain `$2b$` bcrypt scheme the
codebase wrote before commit c6a91396 upgraded it.
"""

from __future__ import annotations

import time

import pytest

from app.utils.passwords import DEFAULT_ROUNDS, MAX_SECRET_BYTES, pwd_context

# --------------------------------------------------------------------------
# Fixtures generated by passlib 1.7.4 + bcrypt 4.0.1. (secret, hash) pairs.
# rounds=4 — the cost is irrelevant to compatibility and the suite is not
# paying 200 ms per assertion to prove otherwise; PASSLIB_V2_PRODUCTION_COST
# below covers the real rounds=12 shape.
# --------------------------------------------------------------------------

LONG_A = "A" * 72 + "0aaaaaaaaa"
LONG_B = "A" * 72 + "0bbbbbbbbb"

PASSLIB_V2 = [
    (
        "correctpw1",
        "$bcrypt-sha256$v=2,t=2b,r=4$y9oBZ09O8JN8BzEneZV4aO$wQRy9qZcuJOX5vMwsByLWRBk11zhck6",
    ),
    ("", "$bcrypt-sha256$v=2,t=2b,r=4$lmcqWPN38j9BGB98RtK4bu$iJyAvEnXO3zK4C1nMuoJd347JE/ZHvO"),
    (
        "Pässwörd123ñ!",
        "$bcrypt-sha256$v=2,t=2b,r=4$mwMUJs8bMP3BGOwJjTxqEu$6RZXmZQXE6LsLcP00T0qZuErryqVDwW",
    ),
    (LONG_A, "$bcrypt-sha256$v=2,t=2b,r=4$xtaO6zI/NbCPcJKNqYry.e$IvvcfrwAXunBtuG63PfeJKVQtQ20jl2"),
    (LONG_B, "$bcrypt-sha256$v=2,t=2b,r=4$UKFY6Mm0b6olrhhurVWCI.$tYvA7yA/KlpwmdX2nx4yIMKocE7QTya"),
    (
        "null\x00inside",
        "$bcrypt-sha256$v=2,t=2b,r=4$hSBVF68LyEW.NkW5i.BuKe$SFK0pT3jk6eb76GcUYZIyjNlbqhnure",
    ),
    (
        "x" * 200,
        "$bcrypt-sha256$v=2,t=2b,r=4$hEDtiOH2f.rCVqqyu0aFLe$n5UpXJw.doydpgtt8L2mzdxB.NR.JoC",
    ),
]

#: A v2 hash at the cost production actually wrote (`r=12`), so the format the
#: column is full of is pinned, not only the cheap variant above.
PASSLIB_V2_PRODUCTION_COST = (
    "correctpw1",
    "$bcrypt-sha256$v=2,t=2b,r=12$LVHCn09sTDqqWIBgE2qmfO$Ueh3vd/tGbPloaok0m/aXtFFv3PAPv.",
)

#: v1 of the wrapper (passlib < 1.7.3): a plain `sha256(password)` pre-hash with
#: no HMAC, and a different string format. Read-only — we never write it.
PASSLIB_V1 = [
    ("correctpw1", "$bcrypt-sha256$2b,4$k1Soze08d3pAaWEVakvtWe$m0xtWZi64wn50X.k9514w8UQ3kF2oiu"),
    ("", "$bcrypt-sha256$2b,4$XW5TFzKADERtH3LuBXnhie$Jx6oOVvU1LxQ4xEBjsRednk/SqznyJe"),
    ("Pässwörd123ñ!", "$bcrypt-sha256$2b,4$iwCGGbI9h.Kk.tFIAB7wAu$vWGWJ7DKM2QDH9IX6T19TWx2KNH3BNO"),
    (LONG_A, "$bcrypt-sha256$2b,4$0dnAxeNDnxPoJ1AkR0oqOu$YpmQagidF7POxAA1SkGBAtY5VTxxg.O"),
    (
        "null\x00inside",
        "$bcrypt-sha256$2b,4$kLupFHWiko2ftWqdR4YS0e$OhOOn09O1/bmuqFeufdYxSDW/7k3DGS",
    ),
    ("x" * 200, "$bcrypt-sha256$2b,4$4BMwyXE2FmVaFYQM.fUM4u$NH4sujmQYn151TEXA8FrpELkPWNHx56"),
]

#: v1 additionally allowed the older `2a` bcrypt variant.
PASSLIB_V1_IDENT_2A = (
    "correctpw1",
    "$bcrypt-sha256$2a,4$H2AIteQt9FD7nSWgR71Nf.$UWyVkUOm82bODxMr0gBrSV9SytnfCB6",
)

#: The scheme the codebase wrote before c6a91396 — raw bcrypt, no pre-hash.
PASSLIB_LEGACY_BCRYPT = [
    ("correctpw1", "$2b$04$0v0ttyuJTPtdZwHxLysDPOJjJ1Xz.Mpi6ky97ySg8ZRBSY5lgOl1i"),
    ("", "$2b$04$CvU0XMMlNt5Gm.Kmh6r/qOdWTlUvhpFiFT7UQi01S0B87t9uDPGxi"),
    ("Pässwörd123ñ!", "$2b$04$7MOxx837cfdMpdd/VgZNPudTFx3p9ISc7JIuVPidiTMqCyLZN/P2O"),
    (LONG_A, "$2b$04$O1jALsnX1PznOmlsZFv9HumWYDokUADoM4JbuRTOYPA4LiBSgVPyy"),
    ("x" * 200, "$2b$04$uvmcL577gEENP0oNqouUQOIJwK6OtnS2qZAX1chFQMX5n7OvVREki"),
]

PASSLIB_LEGACY_IDENT_2A = (
    "correctpw1",
    "$2a$04$GpH1Htt7PIdriSrOhBj1B.uH7pqd1yQrMt7bUQndKmjXVwGMTlSPO",
)
PASSLIB_LEGACY_IDENT_2Y = (
    "correctpw1",
    "$2y$04$F8KSk5RJPVSalQvWnpYxTuc9VDjuZJLk6lMANW0s56vcExLaWWnmW",
)

#: Already relied upon by tests/test_auth_error_consistency.py, which hard-coded
#: it back when passlib generated it. Pinned here too — if this stops verifying,
#: that file's whole login-parity suite is testing nothing.
AUTH_TEST_FIXTURE = (
    "correctpw1",
    "$bcrypt-sha256$v=2,t=2b,r=12$Jl.B.u9pD6kCuDNdO0nFfu$cK3Jg2DYkqzysEPJ0Q1opQpBVRQtyka",
)


# --------------------------------------------------------------------------
# The compatibility contract
# --------------------------------------------------------------------------


@pytest.mark.parametrize("secret,hashed", PASSLIB_V2, ids=lambda v: None)
def test_v2_hashes_written_by_passlib_still_verify(secret: str, hashed: str):
    assert pwd_context.verify(secret, hashed) is True
    assert pwd_context.verify(secret + "x", hashed) is False


@pytest.mark.parametrize("secret,hashed", PASSLIB_V1, ids=lambda v: None)
def test_v1_hashes_written_by_passlib_still_verify(secret: str, hashed: str):
    """The HMAC landed in passlib 1.7.3; v1 rows are plain-sha256 pre-hashes."""
    assert pwd_context.verify(secret, hashed) is True
    assert pwd_context.verify(secret + "x", hashed) is False


def test_v1_hash_with_the_legacy_2a_variant_still_verifies():
    secret, hashed = PASSLIB_V1_IDENT_2A
    assert pwd_context.verify(secret, hashed) is True


def test_a_v2_hash_at_the_production_cost_verifies():
    secret, hashed = PASSLIB_V2_PRODUCTION_COST
    assert f",r={DEFAULT_ROUNDS}$" in hashed, "fixture no longer matches the configured cost"
    assert pwd_context.verify(secret, hashed) is True


def test_the_hash_hardcoded_in_the_login_parity_suite_still_verifies():
    secret, hashed = AUTH_TEST_FIXTURE
    assert pwd_context.verify(secret, hashed) is True
    assert pwd_context.verify("wrong-pw", hashed) is False


@pytest.mark.parametrize("secret,hashed", PASSLIB_LEGACY_BCRYPT, ids=lambda v: None)
def test_pre_upgrade_plain_bcrypt_hashes_still_verify(secret: str, hashed: str):
    """Before c6a91396 the context was passlib's raw-bcrypt scheme, no pre-hash.

    Any row written then is a raw `$2b$` hash. passlib kept verifying those
    (`deprecated=["bcrypt"]`), so we must too — dropping the arm would lock out
    every user who has not changed their password since.
    """
    assert pwd_context.verify(secret, hashed) is True
    if len(secret.encode()) < 72:
        # A longer secret's extra bytes are past bcrypt's 72-byte cut, so they
        # cannot change the answer — that IS the truncation, asserted positively
        # in test_a_long_password_truncates_on_the_legacy_scheme_and_not_on_ours.
        assert pwd_context.verify(secret + "x", hashed) is False


@pytest.mark.parametrize(
    "fixture",
    [PASSLIB_LEGACY_IDENT_2A, PASSLIB_LEGACY_IDENT_2Y],
    ids=["2a", "2y"],
)
def test_plain_bcrypt_hashes_with_other_idents_verify(fixture: tuple[str, str]):
    secret, hashed = fixture
    assert pwd_context.verify(secret, hashed) is True


def test_a_long_password_truncates_on_the_legacy_scheme_and_not_on_ours():
    """The reason `bcrypt_sha256` exists, asserted from both sides.

    Raw bcrypt stops at 72 bytes, so two passwords sharing that prefix verify
    against each other's hash — an attacker who guesses the prefix is done. The
    pre-hash removes that, and the legacy arm must still reproduce it or a
    pre-upgrade password longer than 72 bytes would stop working.
    """
    legacy_long_a = dict(PASSLIB_LEGACY_BCRYPT)[LONG_A]
    assert pwd_context.verify(LONG_B, legacy_long_a) is True, (
        "the legacy arm no longer truncates — a pre-upgrade user with a >72-byte "
        "password can no longer log in"
    )

    v2_long_a = dict(PASSLIB_V2)[LONG_A]
    assert pwd_context.verify(LONG_A, v2_long_a) is True
    assert pwd_context.verify(LONG_B, v2_long_a) is False, "the pre-hash is gone"


# --------------------------------------------------------------------------
# Our own output: same format, same scheme, fresh salt each time
# --------------------------------------------------------------------------


def test_our_hash_is_the_v2_format_and_round_trips():
    hashed = pwd_context.hash("Correct-Horse-1234")
    assert hashed.startswith(f"$bcrypt-sha256$v=2,t=2b,r={DEFAULT_ROUNDS}$")
    # ['', 'bcrypt-sha256', 'v=2,t=2b,r=12', <22-char salt>, <31-char checksum>]
    fields = hashed.split("$")
    assert len(fields) == 5
    assert len(fields[3]) == 22
    assert len(fields[4]) == 31
    assert pwd_context.verify("Correct-Horse-1234", hashed) is True
    assert pwd_context.verify("Correct-Horse-1235", hashed) is False


def test_the_salt_lands_in_the_restricted_final_character_set():
    """bcrypt's 22-char salt carries four unused bits in its last character.

    Implementations disagree on how to hash a salt whose padding bits are set,
    so passlib forced them to zero — which restricts the final character to
    `.Oeu`. Our salts come from `bcrypt.gensalt`, which encodes exactly 16
    bytes and therefore has the property by construction; assert it, because a
    salt that lost it would produce digests other bcrypt builds disagree with.
    """
    for _ in range(25):
        salt = pwd_context.hash("Correct-Horse-1234").split("$")[3]
        assert salt[-1] in ".Oeu", salt


def test_two_hashes_of_the_same_password_differ():
    assert pwd_context.hash("Correct-Horse-1") != pwd_context.hash("Correct-Horse-1")


# --------------------------------------------------------------------------
# Fail closed, never raise — several call sites pass the column verbatim
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "hashed",
    [
        "",
        "not-a-hash",
        "$bcrypt-sha256$",
        "$bcrypt-sha256$v=2,t=2b,r=4$tooshort$tooshort",
        # v=1 in the v2 template, and v=3: passlib raised on both.
        "$bcrypt-sha256$v=1,t=2b,r=4$y9oBZ09O8JN8BzEneZV4aO$wQRy9qZcuJOX5vMwsByLWRBk11zhck6",
        "$bcrypt-sha256$v=3,t=2b,r=4$y9oBZ09O8JN8BzEneZV4aO$wQRy9qZcuJOX5vMwsByLWRBk11zhck6",
        # Right shape, wrong bcrypt variant for v2 (only `2b` was ever written).
        "$bcrypt-sha256$v=2,t=2a,r=4$y9oBZ09O8JN8BzEneZV4aO$wQRy9qZcuJOX5vMwsByLWRBk11zhck6",
        # A too-short salt does not raise out of bcrypt's Rust extension, it
        # PANICS — `pyo3_runtime.PanicException` is a BaseException, so no
        # `except ValueError` catches it. The shape regex has to reject this
        # before `checkpw` ever sees it.
        "$2b$04$way-too-short",
        "$2b$04$" + "!" * 53,
        # crypt_blowfish's buggy 8-bit `$2x$` variant. bcrypt happily hashes it
        # as 2a; passlib refused it outright and so do we — nothing here ever
        # wrote one, so a row carrying it is corruption, not a credential.
        "$2x$04$0v0ttyuJTPtdZwHxLysDPOJjJ1Xz.Mpi6ky97ySg8ZRBSY5lgOl1i",
        # Cost outside bcrypt's 4..31 — a ValueError from the library, not a panic.
        "$2b$00$0v0ttyuJTPtdZwHxLysDPOJjJ1Xz.Mpi6ky97ySg8ZRBSY5lgOl1i",
        "$5$rounds=1000$sha-crypt-is-not-ours",
        "plaintext-password",
        "$2b$04$0v0ttyuJTPtdZwHxLysDPOJjJ1Xz.Mpi6ky97ySg8ZRBSY5lgOl1í",  # non-ascii
    ],
)
def test_a_malformed_or_foreign_hash_returns_false_rather_than_raising(hashed: str):
    """A 500 on the login path would be worse than a refusal, and an
    `hashed_password` column can hold anything a past migration put there."""
    assert pwd_context.verify("correctpw1", hashed) is False


def test_verify_tolerates_a_missing_hash():
    assert pwd_context.verify("correctpw1", None) is False  # type: ignore[arg-type]


def test_an_absurdly_long_secret_is_refused_on_write_but_still_costs_a_full_verify():
    """The ceiling is a write-side guard only, and that asymmetry is the point.

    `hash` refuses beyond `MAX_SECRET_BYTES` (passlib's own ceiling) — unreachable
    from any route, since every password-setting schema caps the field at 128
    characters, so reaching it is a programming error worth hearing about.

    `verify` must NOT refuse: `LoginRequest.password` has no maximum, so a fast
    rejection there would answer "does this account exist?" in microseconds where
    a wrong password costs ~200 ms of bcrypt — the enumeration oracle
    `dummy_verify` exists to close, handed straight back. An oversized secret
    therefore takes the normal path and returns a normal False.
    """
    huge = "a" * (MAX_SECRET_BYTES + 1)
    with pytest.raises(ValueError):
        pwd_context.hash(huge)
    assert pwd_context.verify(huge, dict(PASSLIB_V2)["correctpw1"]) is False


def test_verify_cost_does_not_depend_on_the_attempted_password_length():
    """The enumeration defence, from the hasher's side.

    Asserted as an order of magnitude, never a tight bound, so it cannot become a
    timing flake: an oversized attempt and an ordinary wrong one must both pay a
    full bcrypt, not one of them an early return.
    """
    hashed = dict(PASSLIB_V2)["correctpw1"]

    start = time.perf_counter()
    assert pwd_context.verify("wrong-password", hashed) is False
    ordinary = time.perf_counter() - start

    start = time.perf_counter()
    assert pwd_context.verify("a" * (MAX_SECRET_BYTES + 1), hashed) is False
    oversized = time.perf_counter() - start

    assert ordinary > 0
    assert 0.2 < oversized / ordinary < 5.0, (
        f"an oversized attempt ({oversized:.4f}s) diverged from an ordinary wrong "
        f"password ({ordinary:.4f}s) — a length-based early return is an "
        f"account-enumeration oracle"
    )


# --------------------------------------------------------------------------
# identify / needs_update — the scheme-migration signal
# --------------------------------------------------------------------------


def test_identify_names_each_scheme():
    assert pwd_context.identify(PASSLIB_V2[0][1]) == "bcrypt_sha256"
    assert pwd_context.identify(PASSLIB_V1[0][1]) == "bcrypt_sha256_v1"
    assert pwd_context.identify(PASSLIB_LEGACY_BCRYPT[0][1]) == "bcrypt"
    assert pwd_context.identify("garbage") is None
    assert pwd_context.identify("") is None


def test_needs_update_flags_exactly_the_schemes_we_no_longer_write():
    """passlib's `deprecated=["bcrypt"]` plus its v1 check, reproduced.

    Nothing consults this yet — re-hashing a legacy credential on its owner's
    next login is an open follow-up — so this is the contract that makes wiring
    it up a small change rather than a re-derivation.
    """
    assert pwd_context.needs_update(pwd_context.hash("Correct-Horse-1234")) is False
    assert pwd_context.needs_update(PASSLIB_V2[0][1]) is False
    assert pwd_context.needs_update(PASSLIB_V1[0][1]) is True
    assert pwd_context.needs_update(PASSLIB_LEGACY_BCRYPT[0][1]) is True
    for scheme in pwd_context.deprecated_schemes:
        assert scheme != pwd_context.scheme
